import Foundation

enum DefaultPacks {
    static let all: [Pack] = [englishB2, idioms, vocabulary, facts]

    // MARK: - English B2 — Phrasal Verbs (45 cards)
    static let englishB2 = Pack(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000001")!,
        title: "English B2",
        description: "Phrasal verbs e idioms de nivel intermedio-avanzado",
        emoji: "🇺🇸",
        language: .english,
        isPremium: false,
        isUserCreated: false,
        cards: [
            Card(phrase: "Give up",
                 type: .phrasalVerb,
                 meaningEN: "To stop trying to do something; to quit.",
                 meaningES: "Rendirse. Dejar de intentarlo.",
                 exampleEN: "Don't give up — you're almost there.",
                 exampleES: "No te rindas — ya casi llegas."),

            Card(phrase: "Hit the wall",
                 type: .idiom,
                 meaningEN: "To reach a point of exhaustion where you can't continue.",
                 meaningES: "Llegar al límite físico o mental; quedarse sin energía.",
                 exampleEN: "I hit the wall at mile 20 of the marathon.",
                 exampleES: "Me topé con la pared en el kilómetro 32."),

            Card(phrase: "Push through",
                 type: .phrasalVerb,
                 meaningEN: "To continue despite difficulty or pain.",
                 meaningES: "Aguantar y seguir adelante a pesar del dolor.",
                 exampleEN: "Push through the last set — you've got this.",
                 exampleES: "Aguanta la última serie — tú puedes."),

            Card(phrase: "Go the extra mile",
                 type: .idiom,
                 meaningEN: "To make more effort than expected.",
                 meaningES: "Dar más de lo requerido; esforzarse al máximo.",
                 exampleEN: "She always goes the extra mile in training.",
                 exampleES: "Siempre da más de lo que se le pide."),

            Card(phrase: "Work out",
                 type: .phrasalVerb,
                 meaningEN: "To exercise; or to develop successfully.",
                 meaningES: "Ejercitarse; también 'resultar bien'.",
                 exampleEN: "I work out every morning before breakfast.",
                 exampleES: "Me ejercito cada mañana antes de desayunar."),

            Card(phrase: "Burn out",
                 type: .phrasalVerb,
                 meaningEN: "To become exhausted from overwork or prolonged stress.",
                 meaningES: "Agotarse por exceso de trabajo o estrés.",
                 exampleEN: "He burned out after working 80-hour weeks.",
                 exampleES: "Se agotó después de trabajar semanas de 80 horas."),

            Card(phrase: "In the zone",
                 type: .idiom,
                 meaningEN: "In a state of peak focus and performance.",
                 meaningES: "En estado de máxima concentración y rendimiento.",
                 exampleEN: "She was completely in the zone during the last rep.",
                 exampleES: "Estaba completamente concentrada en la última repetición."),

            Card(phrase: "Step up",
                 type: .phrasalVerb,
                 meaningEN: "To increase effort or take on more responsibility.",
                 meaningES: "Aumentar el esfuerzo o asumir más responsabilidad.",
                 exampleEN: "You need to step up your game if you want to compete.",
                 exampleES: "Necesitas subir tu nivel si quieres competir."),

            Card(phrase: "No pain, no gain",
                 type: .idiom,
                 meaningEN: "You have to work hard to achieve success.",
                 meaningES: "Sin esfuerzo no hay recompensa.",
                 exampleEN: "Keep going — no pain, no gain.",
                 exampleES: "Sigue adelante — sin esfuerzo no hay recompensa."),

            Card(phrase: "Pull through",
                 type: .phrasalVerb,
                 meaningEN: "To recover from a difficult situation or illness.",
                 meaningES: "Salir adelante de una situación difícil o enfermedad.",
                 exampleEN: "He pulled through after months of rehab.",
                 exampleES: "Salió adelante después de meses de rehabilitación."),

            Card(phrase: "Bite the bullet",
                 type: .idiom,
                 meaningEN: "To endure a painful situation with courage.",
                 meaningES: "Aguantar con valentía algo doloroso o difícil.",
                 exampleEN: "Just bite the bullet and do the last set.",
                 exampleES: "Agúantate y haz la última serie."),

            Card(phrase: "Level up",
                 type: .phrasalVerb,
                 meaningEN: "To improve skills or reach a higher standard.",
                 meaningES: "Mejorar habilidades o alcanzar un nivel superior.",
                 exampleEN: "This program will help you level up your strength.",
                 exampleES: "Este programa te ayudará a subir tu nivel de fuerza."),

            Card(phrase: "On the ropes",
                 type: .idiom,
                 meaningEN: "In a very difficult or near-defeat situation.",
                 meaningES: "En una situación muy difícil, al borde del límite.",
                 exampleEN: "He was on the ropes in the final round.",
                 exampleES: "Estaba al límite en el último round."),

            Card(phrase: "Bounce back",
                 type: .phrasalVerb,
                 meaningEN: "To recover quickly after a setback or failure.",
                 meaningES: "Recuperarse rápidamente después de un revés.",
                 exampleEN: "Great athletes always bounce back from injuries.",
                 exampleES: "Los grandes atletas siempre se recuperan de las lesiones."),

            Card(phrase: "Second wind",
                 type: .idiom,
                 meaningEN: "A new burst of energy after feeling tired.",
                 meaningES: "Un segundo aire; energía renovada después del cansancio.",
                 exampleEN: "I got my second wind in the last kilometer.",
                 exampleES: "Me llegó el segundo aire en el último kilómetro."),

            Card(phrase: "Set up",
                 type: .phrasalVerb,
                 meaningEN: "To arrange or prepare something; to establish.",
                 meaningES: "Preparar o configurar algo; establecer.",
                 exampleEN: "She set up a new training routine from scratch.",
                 exampleES: "Preparó una nueva rutina de entrenamiento desde cero."),

            Card(phrase: "Break down",
                 type: .phrasalVerb,
                 meaningEN: "To stop functioning; to lose emotional control; to analyze.",
                 meaningES: "Dejar de funcionar; perder el control emocional; analizar.",
                 exampleEN: "He broke down after the race and started crying.",
                 exampleES: "Se derrumbó emocionalmente después de la carrera."),

            Card(phrase: "Carry out",
                 type: .phrasalVerb,
                 meaningEN: "To complete or perform a task.",
                 meaningES: "Llevar a cabo una tarea o plan.",
                 exampleEN: "They carried out the experiment successfully.",
                 exampleES: "Llevaron a cabo el experimento exitosamente."),

            Card(phrase: "Take off",
                 type: .phrasalVerb,
                 meaningEN: "To remove; to leave quickly; to become successful.",
                 meaningES: "Quitarse; irse rápido; despegar (tener éxito).",
                 exampleEN: "His career really took off after that performance.",
                 exampleES: "Su carrera despegó después de esa actuación."),

            Card(phrase: "Look into",
                 type: .phrasalVerb,
                 meaningEN: "To investigate or research something.",
                 meaningES: "Investigar o examinar algo.",
                 exampleEN: "I'll look into better recovery techniques.",
                 exampleES: "Voy a investigar mejores técnicas de recuperación."),

            Card(phrase: "Bring up",
                 type: .phrasalVerb,
                 meaningEN: "To mention a topic; to raise a child.",
                 meaningES: "Mencionar un tema; criar a un niño.",
                 exampleEN: "He brought up the issue of nutrition during the meeting.",
                 exampleES: "Sacó el tema de la nutrición durante la reunión."),

            Card(phrase: "Call off",
                 type: .phrasalVerb,
                 meaningEN: "To cancel something that was planned.",
                 meaningES: "Cancelar algo que estaba planeado.",
                 exampleEN: "They called off the race due to bad weather.",
                 exampleES: "Cancelaron la carrera por el mal tiempo."),

            Card(phrase: "Put off",
                 type: .phrasalVerb,
                 meaningEN: "To postpone; to delay doing something.",
                 meaningES: "Posponer; aplazar hacer algo.",
                 exampleEN: "Stop putting off your workout — just go.",
                 exampleES: "Deja de posponer tu entrenamiento — simplemente ve."),

            Card(phrase: "Run into",
                 type: .phrasalVerb,
                 meaningEN: "To encounter unexpectedly; to crash into.",
                 meaningES: "Encontrarse con algo inesperadamente; chocar con.",
                 exampleEN: "I ran into my old coach at the gym.",
                 exampleES: "Me encontré con mi antiguo entrenador en el gimnasio."),

            Card(phrase: "Stand out",
                 type: .phrasalVerb,
                 meaningEN: "To be clearly better or more noticeable than others.",
                 meaningES: "Destacarse; ser claramente mejor o más notable.",
                 exampleEN: "Her dedication made her stand out from the team.",
                 exampleES: "Su dedicación la hizo destacar del equipo."),

            Card(phrase: "Come up with",
                 type: .phrasalVerb,
                 meaningEN: "To think of an idea or a solution.",
                 meaningES: "Ocurrírsele una idea o solución a alguien.",
                 exampleEN: "He came up with a brilliant training hack.",
                 exampleES: "Se le ocurrió un truco genial de entrenamiento."),

            Card(phrase: "Put up with",
                 type: .phrasalVerb,
                 meaningEN: "To tolerate something unpleasant.",
                 meaningES: "Aguantar o tolerar algo desagradable.",
                 exampleEN: "I can't put up with poor form — fix it.",
                 exampleES: "No puedo tolerar mala técnica — corrígela."),

            Card(phrase: "Look up to",
                 type: .phrasalVerb,
                 meaningEN: "To admire and respect someone.",
                 meaningES: "Admirar y respetar a alguien.",
                 exampleEN: "Many young athletes look up to him.",
                 exampleES: "Muchos atletas jóvenes lo admiran."),

            Card(phrase: "Let down",
                 type: .phrasalVerb,
                 meaningEN: "To disappoint someone.",
                 meaningES: "Decepcionar a alguien.",
                 exampleEN: "Don't let your team down — finish strong.",
                 exampleES: "No decepciones a tu equipo — termina fuerte."),

            Card(phrase: "Figure out",
                 type: .phrasalVerb,
                 meaningEN: "To understand or find a solution to something.",
                 meaningES: "Entender o encontrar la solución a algo.",
                 exampleEN: "I finally figured out why my squat was wrong.",
                 exampleES: "Por fin entendí por qué mi sentadilla estaba mal."),

            Card(phrase: "Turn down",
                 type: .phrasalVerb,
                 meaningEN: "To refuse an offer or request.",
                 meaningES: "Rechazar una oferta o solicitud.",
                 exampleEN: "She turned down the sponsorship deal.",
                 exampleES: "Rechazó el trato de patrocinio."),

            Card(phrase: "Move on",
                 type: .phrasalVerb,
                 meaningEN: "To stop dwelling on something and continue forward.",
                 meaningES: "Dejar de pensar en algo y seguir adelante.",
                 exampleEN: "You lost the match — move on and train harder.",
                 exampleES: "Perdiste el partido — supéralo y entrena más duro."),

            Card(phrase: "Take on",
                 type: .phrasalVerb,
                 meaningEN: "To accept a challenge or hire someone.",
                 meaningES: "Aceptar un desafío o contratar a alguien.",
                 exampleEN: "He took on the challenge of running a 100-mile race.",
                 exampleES: "Aceptó el desafío de correr una carrera de 100 millas."),

            Card(phrase: "Build up",
                 type: .phrasalVerb,
                 meaningEN: "To gradually increase or develop something.",
                 meaningES: "Desarrollar o aumentar algo gradualmente.",
                 exampleEN: "Build up your mileage slowly to avoid injury.",
                 exampleES: "Aumenta tu kilometraje poco a poco para evitar lesiones."),

            Card(phrase: "Catch up",
                 type: .phrasalVerb,
                 meaningEN: "To reach the same level as someone ahead of you.",
                 meaningES: "Alcanzar el mismo nivel que alguien que va adelante.",
                 exampleEN: "He trained twice a day to catch up with the others.",
                 exampleES: "Entrenó dos veces al día para alcanzar a los demás."),

            Card(phrase: "Cut down",
                 type: .phrasalVerb,
                 meaningEN: "To reduce the amount of something.",
                 meaningES: "Reducir la cantidad de algo.",
                 exampleEN: "Cut down on sugar if you want better results.",
                 exampleES: "Reduce el azúcar si quieres mejores resultados."),

            Card(phrase: "Run out",
                 type: .phrasalVerb,
                 meaningEN: "To use up all of a supply; to have nothing left.",
                 meaningES: "Quedarse sin algo; agotar una reserva.",
                 exampleEN: "I ran out of energy before the finish line.",
                 exampleES: "Me quedé sin energía antes de la línea de meta."),

            Card(phrase: "Wear out",
                 type: .phrasalVerb,
                 meaningEN: "To become exhausted or damaged from use.",
                 meaningES: "Agotarse o desgastarse por el uso.",
                 exampleEN: "Don't wear yourself out before the competition.",
                 exampleES: "No te agotes antes de la competencia."),

            Card(phrase: "Pick up",
                 type: .phrasalVerb,
                 meaningEN: "To lift something; to learn quickly; to improve.",
                 meaningES: "Levantar algo; aprender rápido; mejorar.",
                 exampleEN: "She picked up Spanish in just six months.",
                 exampleES: "Aprendió español en solo seis meses."),

            Card(phrase: "Kick off",
                 type: .phrasalVerb,
                 meaningEN: "To start something; to begin an event.",
                 meaningES: "Comenzar algo; iniciar un evento.",
                 exampleEN: "The season kicks off next Monday.",
                 exampleES: "La temporada comienza el próximo lunes."),

            Card(phrase: "Keep up",
                 type: .phrasalVerb,
                 meaningEN: "To maintain the same speed or level as others.",
                 meaningES: "Mantener el mismo ritmo o nivel que otros.",
                 exampleEN: "He struggled to keep up with the pace.",
                 exampleES: "Le costó mantener el ritmo."),

            Card(phrase: "Break through",
                 type: .phrasalVerb,
                 meaningEN: "To overcome an obstacle or reach a new level.",
                 meaningES: "Superar un obstáculo o alcanzar un nuevo nivel.",
                 exampleEN: "She finally broke through her plateau.",
                 exampleES: "Por fin superó su estancamiento."),

            Card(phrase: "Dial in",
                 type: .phrasalVerb,
                 meaningEN: "To fine-tune or optimize something precisely.",
                 meaningES: "Afinar o optimizar algo con precisión.",
                 exampleEN: "He dialed in his nutrition before the competition.",
                 exampleES: "Afinó su nutrición antes de la competencia."),

            Card(phrase: "Ease up",
                 type: .phrasalVerb,
                 meaningEN: "To reduce intensity or pressure; to relax.",
                 meaningES: "Reducir la intensidad o presión; relajarse.",
                 exampleEN: "Ease up on the weight — technique first.",
                 exampleES: "Reduce el peso — la técnica primero."),

            Card(phrase: "Zone out",
                 type: .phrasalVerb,
                 meaningEN: "To lose focus or become distracted.",
                 meaningES: "Perder la concentración; desconectarse mentalmente.",
                 exampleEN: "Don't zone out between sets — stay focused.",
                 exampleES: "No te desconectes entre series — mantén el foco."),
        ]
    )

    // MARK: - Power Idioms (30 cards)
    static let idioms = Pack(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000002")!,
        title: "Power Idioms",
        description: "Expresiones que suenan como nativo",
        emoji: "🧠",
        language: .english,
        isPremium: false,
        isUserCreated: false,
        cards: [
            Card(phrase: "Burn the midnight oil",
                 type: .idiom,
                 meaningEN: "To work or study very late into the night.",
                 meaningES: "Trabajar o estudiar hasta muy tarde; quemarse las pestañas.",
                 exampleEN: "She burned the midnight oil to finish the project.",
                 exampleES: "Se quemó las pestañas para terminar el proyecto."),

            Card(phrase: "Bite off more than you can chew",
                 type: .idiom,
                 meaningEN: "To take on more responsibility than you can handle.",
                 meaningES: "Abarcar más de lo que uno puede manejar.",
                 exampleEN: "He bit off more than he could chew with three jobs.",
                 exampleES: "Abarcó más de lo que podía con tres trabajos."),

            Card(phrase: "Cut corners",
                 type: .idiom,
                 meaningEN: "To do something the easy way, sacrificing quality.",
                 meaningES: "Hacer algo de manera fácil sacrificando calidad.",
                 exampleEN: "Don't cut corners on your form to lift more weight.",
                 exampleES: "No sacrifiques la técnica para levantar más peso."),

            Card(phrase: "Hit the ground running",
                 type: .idiom,
                 meaningEN: "To start something with great energy and no delay.",
                 meaningES: "Comenzar algo con mucha energía desde el principio.",
                 exampleEN: "He hit the ground running on his first day.",
                 exampleES: "Arrancó con todo desde su primer día."),

            Card(phrase: "The ball is in your court",
                 type: .idiom,
                 meaningEN: "It's your turn to take action or make a decision.",
                 meaningES: "Es tu turno de actuar o tomar una decisión.",
                 exampleEN: "I've done my part — the ball is in your court.",
                 exampleES: "Ya hice mi parte — ahora te toca a ti."),

            Card(phrase: "Under the weather",
                 type: .idiom,
                 meaningEN: "Feeling ill or not well.",
                 meaningES: "Sentirse mal o enfermo.",
                 exampleEN: "I'm skipping the gym — feeling a bit under the weather.",
                 exampleES: "Me salto el gym — no me siento muy bien."),

            Card(phrase: "Bite the dust",
                 type: .idiom,
                 meaningEN: "To fail or be defeated; to die.",
                 meaningES: "Fracasar, ser derrotado; también morir.",
                 exampleEN: "His PR attempt bit the dust at the last second.",
                 exampleES: "Su intento de récord fracasó en el último segundo."),

            Card(phrase: "On thin ice",
                 type: .idiom,
                 meaningEN: "In a risky or precarious situation.",
                 meaningES: "En una situación arriesgada o precaria.",
                 exampleEN: "Skip one more session and you're on thin ice.",
                 exampleES: "Falta una sesión más y estarás en terreno peligroso."),

            Card(phrase: "Back to square one",
                 type: .idiom,
                 meaningEN: "To start over from the beginning after a failure.",
                 meaningES: "Empezar de cero después de un fracaso.",
                 exampleEN: "The injury sent him back to square one.",
                 exampleES: "La lesión lo mandó de vuelta al principio."),

            Card(phrase: "Beat around the bush",
                 type: .idiom,
                 meaningEN: "To avoid talking about the main point.",
                 meaningES: "Andarse por las ramas; evitar el punto principal.",
                 exampleEN: "Stop beating around the bush — tell me your time.",
                 exampleES: "Deja de rodeos — dime tu tiempo."),

            Card(phrase: "Get the ball rolling",
                 type: .idiom,
                 meaningEN: "To start a process or activity.",
                 meaningES: "Poner las cosas en marcha; iniciar un proceso.",
                 exampleEN: "Let's get the ball rolling on the new training block.",
                 exampleES: "Pongamos en marcha el nuevo bloque de entrenamiento."),

            Card(phrase: "Hit the nail on the head",
                 type: .idiom,
                 meaningEN: "To describe or identify something exactly right.",
                 meaningES: "Dar en el clavo; describir algo con exactitud.",
                 exampleEN: "You hit the nail on the head with that diagnosis.",
                 exampleES: "Diste en el clavo con ese diagnóstico."),

            Card(phrase: "Throw in the towel",
                 type: .idiom,
                 meaningEN: "To admit defeat and give up.",
                 meaningES: "Tirar la toalla; admitir la derrota.",
                 exampleEN: "He refused to throw in the towel despite the pain.",
                 exampleES: "Se negó a tirar la toalla a pesar del dolor."),

            Card(phrase: "Spill the beans",
                 type: .idiom,
                 meaningEN: "To reveal secret or private information.",
                 meaningES: "Revelar información secreta o privada.",
                 exampleEN: "Don't spill the beans about the surprise event.",
                 exampleES: "No cuentes nada sobre el evento sorpresa."),

            Card(phrase: "Out of the blue",
                 type: .idiom,
                 meaningEN: "Suddenly and unexpectedly.",
                 meaningES: "De repente y de forma inesperada.",
                 exampleEN: "Out of the blue, he broke the world record.",
                 exampleES: "De la nada, rompió el récord mundial."),

            Card(phrase: "Let the cat out of the bag",
                 type: .idiom,
                 meaningEN: "To accidentally reveal a secret.",
                 meaningES: "Revelar un secreto sin querer.",
                 exampleEN: "She let the cat out of the bag about the new program.",
                 exampleES: "Reveló sin querer el nuevo programa."),

            Card(phrase: "The tip of the iceberg",
                 type: .idiom,
                 meaningEN: "A small visible part of a much larger problem.",
                 meaningES: "La pequeña parte visible de un problema mucho mayor.",
                 exampleEN: "That soreness is just the tip of the iceberg.",
                 exampleES: "Ese dolor muscular es solo la punta del iceberg."),

            Card(phrase: "Every cloud has a silver lining",
                 type: .idiom,
                 meaningEN: "Every bad situation has a positive aspect.",
                 meaningES: "Todo tiene su lado positivo; no hay mal que por bien no venga.",
                 exampleEN: "Losing taught me a lot — every cloud has a silver lining.",
                 exampleES: "Perder me enseñó mucho — no hay mal que por bien no venga."),

            Card(phrase: "Go back to the drawing board",
                 type: .idiom,
                 meaningEN: "To start planning something again from the beginning.",
                 meaningES: "Volver a empezar desde cero con un plan.",
                 exampleEN: "The strategy failed — let's go back to the drawing board.",
                 exampleES: "La estrategia falló — a replantear todo desde cero."),

            Card(phrase: "Don't judge a book by its cover",
                 type: .idiom,
                 meaningEN: "Don't form an opinion based on appearances alone.",
                 meaningES: "No juzgues por las apariencias.",
                 exampleEN: "He doesn't look strong, but don't judge a book by its cover.",
                 exampleES: "No parece fuerte, pero no te dejes llevar por las apariencias."),

            Card(phrase: "Bend over backwards",
                 type: .idiom,
                 meaningEN: "To make a great effort to help or please someone.",
                 meaningES: "Hacer todo lo posible por ayudar a alguien.",
                 exampleEN: "The coach bent over backwards to help the team.",
                 exampleES: "El entrenador hizo todo lo posible por ayudar al equipo."),

            Card(phrase: "Up in the air",
                 type: .idiom,
                 meaningEN: "Uncertain or undecided.",
                 meaningES: "Incierto o sin decidir.",
                 exampleEN: "The competition date is still up in the air.",
                 exampleES: "La fecha de la competencia sigue sin definirse."),

            Card(phrase: "See eye to eye",
                 type: .idiom,
                 meaningEN: "To agree with someone.",
                 meaningES: "Estar de acuerdo con alguien; ver las cosas igual.",
                 exampleEN: "The coach and athlete don't always see eye to eye.",
                 exampleES: "El entrenador y el atleta no siempre están de acuerdo."),

            Card(phrase: "Break the ice",
                 type: .idiom,
                 meaningEN: "To do something to reduce tension or awkwardness.",
                 meaningES: "Romper el hielo; reducir la tensión o incomodidad.",
                 exampleEN: "He told a joke to break the ice before the race.",
                 exampleES: "Contó un chiste para romper el hielo antes de la carrera."),

            Card(phrase: "Face the music",
                 type: .idiom,
                 meaningEN: "To accept the consequences of your actions.",
                 meaningES: "Asumir las consecuencias de tus actos.",
                 exampleEN: "You missed training for a week — now face the music.",
                 exampleES: "Faltaste una semana — ahora asume las consecuencias."),

            Card(phrase: "The elephant in the room",
                 type: .idiom,
                 meaningEN: "An obvious problem that everyone avoids discussing.",
                 meaningES: "Un problema evidente que todos evitan mencionar.",
                 exampleEN: "His injury is the elephant in the room for the team.",
                 exampleES: "Su lesión es el tema que todos evitan en el equipo."),

            Card(phrase: "Hang in there",
                 type: .idiom,
                 meaningEN: "To persist through a difficult situation.",
                 meaningES: "Aguantar; persistir en una situación difícil.",
                 exampleEN: "Hang in there — the last week is always the hardest.",
                 exampleES: "Aguanta — la última semana siempre es la más dura."),

            Card(phrase: "Once in a blue moon",
                 type: .idiom,
                 meaningEN: "Very rarely; almost never.",
                 meaningES: "Muy de vez en cuando; casi nunca.",
                 exampleEN: "He only skips a workout once in a blue moon.",
                 exampleES: "Casi nunca se salta un entrenamiento."),

            Card(phrase: "Pull someone's leg",
                 type: .idiom,
                 meaningEN: "To joke or tease someone.",
                 meaningES: "Tomarle el pelo a alguien; bromear.",
                 exampleEN: "Are you serious or just pulling my leg?",
                 exampleES: "¿Hablas en serio o me estás tomando el pelo?"),

            Card(phrase: "Keep your chin up",
                 type: .idiom,
                 meaningEN: "Stay positive and don't give up in a hard situation.",
                 meaningES: "Mantén el ánimo; no te rindas ante la adversidad.",
                 exampleEN: "Keep your chin up — you'll get your PR soon.",
                 exampleES: "Ánimo — pronto lograrás tu récord personal."),
        ]
    )

    // MARK: - Everyday Vocabulary (25 cards)
    static let vocabulary = Pack(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000004")!,
        title: "Everyday Vocab",
        description: "Palabras esenciales para sonar fluido",
        emoji: "📖",
        language: .english,
        isPremium: false,
        isUserCreated: false,
        cards: [
            Card(phrase: "Resilient",
                 type: .custom,
                 meaningEN: "Able to recover quickly from difficulties.",
                 meaningES: "Resiliente; capaz de recuperarse rápido de las dificultades.",
                 exampleEN: "A resilient mindset is key to long-term success.",
                 exampleES: "Una mentalidad resiliente es clave para el éxito a largo plazo."),

            Card(phrase: "Consistent",
                 type: .custom,
                 meaningEN: "Doing something the same way over time; reliable.",
                 meaningES: "Constante; que hace algo de la misma manera con el tiempo.",
                 exampleEN: "Being consistent beats being intense.",
                 exampleES: "Ser constante supera a ser intenso."),

            Card(phrase: "Momentum",
                 type: .custom,
                 meaningEN: "The force or energy that keeps something moving forward.",
                 meaningES: "El impulso o energía que mantiene algo en movimiento.",
                 exampleEN: "Don't lose your momentum — keep the streak going.",
                 exampleES: "No pierdas el impulso — mantén la racha."),

            Card(phrase: "Deliberate",
                 type: .custom,
                 meaningEN: "Done with purpose and careful thought; intentional.",
                 meaningES: "Hecho con propósito y cuidado; intencional.",
                 exampleEN: "Deliberate practice leads to faster improvement.",
                 exampleES: "La práctica deliberada lleva a una mejora más rápida."),

            Card(phrase: "Threshold",
                 type: .custom,
                 meaningEN: "The point at which something begins to change.",
                 meaningES: "El umbral; el punto en el que algo comienza a cambiar.",
                 exampleEN: "Train near your threshold to improve endurance.",
                 exampleES: "Entrena cerca de tu umbral para mejorar la resistencia."),

            Card(phrase: "Perseverance",
                 type: .custom,
                 meaningEN: "Continued effort despite difficulty or delay.",
                 meaningES: "Perseverancia; esfuerzo continuo a pesar de las dificultades.",
                 exampleEN: "Perseverance is more important than talent.",
                 exampleES: "La perseverancia es más importante que el talento."),

            Card(phrase: "Tenacious",
                 type: .custom,
                 meaningEN: "Very determined; not giving up easily.",
                 meaningES: "Tenaz; muy determinado, que no se rinde fácilmente.",
                 exampleEN: "She's a tenacious competitor who never quits.",
                 exampleES: "Es una competidora tenaz que nunca se rinde."),

            Card(phrase: "Discipline",
                 type: .custom,
                 meaningEN: "The ability to do what needs to be done consistently.",
                 meaningES: "La disciplina; hacer lo necesario de manera constante.",
                 exampleEN: "Discipline is choosing the long game over instant comfort.",
                 exampleES: "La disciplina es elegir el largo plazo sobre el confort inmediato."),

            Card(phrase: "Grueling",
                 type: .custom,
                 meaningEN: "Exhausting and demanding; extremely tiring.",
                 meaningES: "Agotador; extremadamente cansado y exigente.",
                 exampleEN: "It was a grueling 5-hour workout.",
                 exampleES: "Fue un entrenamiento agotador de 5 horas."),

            Card(phrase: "Endurance",
                 type: .custom,
                 meaningEN: "The ability to sustain prolonged physical or mental effort.",
                 meaningES: "Resistencia; capacidad de sostener el esfuerzo prolongado.",
                 exampleEN: "Build endurance before you build speed.",
                 exampleES: "Desarrolla la resistencia antes de la velocidad."),

            Card(phrase: "Plateau",
                 type: .custom,
                 meaningEN: "A period when progress stops or levels off.",
                 meaningES: "Meseta; período en el que el progreso se estanca.",
                 exampleEN: "Hit a plateau? Change your stimulus.",
                 exampleES: "¿Llegaste a una meseta? Cambia el estímulo."),

            Card(phrase: "Overwhelmed",
                 type: .custom,
                 meaningEN: "Feeling buried by too much at once.",
                 meaningES: "Abrumado; sentirse superado por demasiadas cosas a la vez.",
                 exampleEN: "When overwhelmed, focus on the next small step.",
                 exampleES: "Cuando te sientas abrumado, enfócate en el siguiente pequeño paso."),

            Card(phrase: "Prioritize",
                 type: .custom,
                 meaningEN: "To decide which things are most important and do them first.",
                 meaningES: "Priorizar; decidir qué es más importante y hacerlo primero.",
                 exampleEN: "Prioritize sleep if you want to perform at your best.",
                 exampleES: "Prioriza el sueño si quieres rendir al máximo."),

            Card(phrase: "Leverage",
                 type: .custom,
                 meaningEN: "To use something to its maximum advantage.",
                 meaningES: "Aprovechar algo al máximo; usar como palanca.",
                 exampleEN: "Leverage your strengths to compensate for weaknesses.",
                 exampleES: "Aprovecha tus fortalezas para compensar las debilidades."),

            Card(phrase: "Mindset",
                 type: .custom,
                 meaningEN: "The established set of attitudes held by someone.",
                 meaningES: "La mentalidad; el conjunto de actitudes que tiene una persona.",
                 exampleEN: "A growth mindset turns failures into lessons.",
                 exampleES: "Una mentalidad de crecimiento convierte los fracasos en lecciones."),

            Card(phrase: "Adamant",
                 type: .custom,
                 meaningEN: "Refusing to change one's mind; very determined.",
                 meaningES: "Inflexible; que se niega a cambiar de opinión; muy determinado.",
                 exampleEN: "She was adamant about following her training plan.",
                 exampleES: "Fue inflexible en cuanto a seguir su plan de entrenamiento."),

            Card(phrase: "Vigorous",
                 type: .custom,
                 meaningEN: "Strong, healthy, and full of energy.",
                 meaningES: "Vigoroso; fuerte, sano y lleno de energía.",
                 exampleEN: "A vigorous warm-up prevents injury.",
                 exampleES: "Un calentamiento vigoroso previene lesiones."),

            Card(phrase: "Relentless",
                 type: .custom,
                 meaningEN: "Unceasingly intense; never stopping or slowing.",
                 meaningES: "Implacable; intenso sin cesar, sin parar ni reducir la velocidad.",
                 exampleEN: "His relentless work ethic set him apart.",
                 exampleES: "Su implacable ética de trabajo lo distinguió."),

            Card(phrase: "Benchmark",
                 type: .custom,
                 meaningEN: "A reference point for measuring progress.",
                 meaningES: "Un punto de referencia para medir el progreso.",
                 exampleEN: "Set a benchmark and try to beat it every month.",
                 exampleES: "Establece un punto de referencia e intenta superarlo cada mes."),

            Card(phrase: "Clutch",
                 type: .custom,
                 meaningEN: "Performing well under pressure; crucial.",
                 meaningES: "Rendir bien bajo presión; decisivo en el momento clave.",
                 exampleEN: "He always comes through in clutch moments.",
                 exampleES: "Siempre responde en los momentos decisivos."),

            Card(phrase: "Grit",
                 type: .custom,
                 meaningEN: "Courage and determination; mental toughness.",
                 meaningES: "Agallas; valentía y determinación; fortaleza mental.",
                 exampleEN: "Talent is common — grit is rare.",
                 exampleES: "El talento es común — las agallas son escasas."),

            Card(phrase: "Volatile",
                 type: .custom,
                 meaningEN: "Likely to change suddenly and unpredictably.",
                 meaningES: "Volátil; propenso a cambiar repentina e impredeciblemente.",
                 exampleEN: "Performance can be volatile during heavy training weeks.",
                 exampleES: "El rendimiento puede ser volátil durante semanas de entrenamiento intenso."),

            Card(phrase: "Intuitive",
                 type: .custom,
                 meaningEN: "Based on instinct rather than conscious reasoning.",
                 meaningES: "Intuitivo; basado en el instinto más que en el razonamiento.",
                 exampleEN: "An experienced athlete has an intuitive feel for pacing.",
                 exampleES: "Un atleta experimentado tiene una sensación intuitiva del ritmo."),

            Card(phrase: "Meticulous",
                 type: .custom,
                 meaningEN: "Very careful and precise about details.",
                 meaningES: "Meticuloso; muy cuidadoso y preciso con los detalles.",
                 exampleEN: "She was meticulous about tracking her macros.",
                 exampleES: "Era meticulosa en el registro de sus macros."),

            Card(phrase: "Conviction",
                 type: .custom,
                 meaningEN: "A strong belief or the quality of showing certainty.",
                 meaningES: "Convicción; creencia firme o certeza en algo.",
                 exampleEN: "Train with conviction and results will follow.",
                 exampleES: "Entrena con convicción y los resultados llegarán."),
        ]
    )

    // MARK: - Datos Curiosos (16 cards)
    static let facts = Pack(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000003")!,
        title: "Datos Curiosos",
        description: "Aprende algo interesante entre series",
        emoji: "🔬",
        language: .spanish,
        isPremium: false,
        isUserCreated: false,
        cards: [
            Card(phrase: "El efecto placebo",
                 type: .fact,
                 meaningEN: "Believing a treatment works can actually make it work.",
                 meaningES: "Creer que un tratamiento funciona puede hacerlo funcionar, aunque sea falso.",
                 exampleEN: "Athletes who think they took supplements perform better.",
                 exampleES: "Atletas que creen haber tomado suplementos rinden mejor."),

            Card(phrase: "Músculo vs grasa",
                 type: .fact,
                 meaningEN: "Muscle is denser than fat — you can weigh more but look leaner.",
                 meaningES: "El músculo es más denso que la grasa — puedes pesar más pero verte más delgado.",
                 exampleEN: "Don't judge progress only by the scale.",
                 exampleES: "No juzgues el progreso solo por la báscula."),

            Card(phrase: "El sueño y los músculos",
                 type: .fact,
                 meaningEN: "Most muscle repair and growth happens during deep sleep.",
                 meaningES: "La mayor parte de la reparación y crecimiento muscular ocurre durante el sueño profundo.",
                 exampleEN: "Sleep is when your gains actually happen.",
                 exampleES: "El sueño es cuando realmente ocurren tus ganancias."),

            Card(phrase: "La regla de los 21 días",
                 type: .fact,
                 meaningEN: "It takes 66 days on average to form a new habit, not 21.",
                 meaningES: "En realidad se necesitan 66 días en promedio para formar un hábito, no 21.",
                 exampleEN: "Be patient with new routines — it takes longer than you think.",
                 exampleES: "Ten paciencia con las rutinas nuevas — toma más de lo que crees."),

            Card(phrase: "Cortisol y entrenamiento",
                 type: .fact,
                 meaningEN: "Too much cortisol can break down muscle instead of building it.",
                 meaningES: "Demasiado cortisol puede destruir músculo en lugar de construirlo.",
                 exampleEN: "Rest days are not laziness — they're part of the program.",
                 exampleES: "Los días de descanso no son flojera — son parte del programa."),

            Card(phrase: "La paradoja del esfuerzo",
                 type: .fact,
                 meaningEN: "Pushing to absolute failure every set may actually slow progress.",
                 meaningES: "Llegar al fallo absoluto en cada serie puede retrasar el progreso.",
                 exampleEN: "Leave 1-2 reps in the tank most sets.",
                 exampleES: "Deja 1-2 repeticiones en el tanque en la mayoría de las series."),

            Card(phrase: "La regla del 1%",
                 type: .fact,
                 meaningEN: "Improving just 1% per day compounds into 37x better in a year.",
                 meaningES: "Mejorar solo un 1% al día se multiplica 37 veces en un año.",
                 exampleEN: "Small improvements add up to massive results.",
                 exampleES: "Las pequeñas mejoras se acumulan en resultados enormes."),

            Card(phrase: "Dopamina y metas",
                 type: .fact,
                 meaningEN: "The brain releases dopamine when you make progress toward a goal.",
                 meaningES: "El cerebro libera dopamina cuando avanzas hacia una meta.",
                 exampleEN: "Celebrate small wins to keep your motivation high.",
                 exampleES: "Celebra las pequeñas victorias para mantener alta tu motivación."),

            Card(phrase: "El calentamiento activo",
                 type: .fact,
                 meaningEN: "A dynamic warm-up improves performance more than static stretching.",
                 meaningES: "Un calentamiento dinámico mejora el rendimiento más que el estiramiento estático.",
                 exampleEN: "Leg swings and lunges beat sitting and holding stretches.",
                 exampleES: "Los balanceos y estocadas superan al estiramiento pasivo."),

            Card(phrase: "Hidratación y fuerza",
                 type: .fact,
                 meaningEN: "Being just 2% dehydrated can reduce strength by up to 10%.",
                 meaningES: "Con solo un 2% de deshidratación, tu fuerza puede bajar hasta un 10%.",
                 exampleEN: "Drink water before you feel thirsty.",
                 exampleES: "Bebe agua antes de sentir sed."),

            Card(phrase: "Respiración y rendimiento",
                 type: .fact,
                 meaningEN: "Nasal breathing during exercise improves oxygen use and endurance.",
                 meaningES: "Respirar por la nariz durante el ejercicio mejora el uso del oxígeno.",
                 exampleEN: "Try nasal breathing at low intensity to train your lungs.",
                 exampleES: "Intenta respirar por la nariz a baja intensidad para entrenar tus pulmones."),

            Card(phrase: "El cold shower effect",
                 type: .fact,
                 meaningEN: "Cold showers can reduce muscle soreness and boost alertness.",
                 meaningES: "Las duchas frías pueden reducir el dolor muscular y aumentar el estado de alerta.",
                 exampleEN: "30 seconds of cold water post-workout makes a difference.",
                 exampleES: "30 segundos de agua fría post-entrenamiento marcan la diferencia."),

            Card(phrase: "Tiempo bajo tensión",
                 type: .fact,
                 meaningEN: "Slowing down reps increases muscle activation and growth.",
                 meaningES: "Hacer las repeticiones más lentas aumenta la activación y el crecimiento muscular.",
                 exampleEN: "Try a 3-second eccentric on every rep.",
                 exampleES: "Prueba una fase excéntrica de 3 segundos en cada repetición."),

            Card(phrase: "La ventana anabólica",
                 type: .fact,
                 meaningEN: "The post-workout protein window is wider than once thought — up to 4 hours.",
                 meaningES: "La ventana anabólica post-entrenamiento es más amplia de lo que se creía — hasta 4 horas.",
                 exampleEN: "You don't need to rush your protein shake.",
                 exampleES: "No necesitas apresurarte con tu batido de proteínas."),

            Card(phrase: "Cafeína y rendimiento",
                 type: .fact,
                 meaningEN: "Caffeine can improve endurance by up to 12% and strength by 3-5%.",
                 meaningES: "La cafeína puede mejorar la resistencia hasta un 12% y la fuerza entre un 3-5%.",
                 exampleEN: "Coffee 45-60 min before training is evidence-based.",
                 exampleES: "El café 45-60 minutos antes del entrenamiento tiene respaldo científico."),

            Card(phrase: "La curva del aprendizaje motor",
                 type: .fact,
                 meaningEN: "New movement patterns take 300-500 repetitions to become automatic.",
                 meaningES: "Los nuevos patrones de movimiento necesitan 300-500 repeticiones para volverse automáticos.",
                 exampleEN: "Be patient when learning a new lift — your brain is wiring it.",
                 exampleES: "Ten paciencia al aprender un nuevo ejercicio — tu cerebro lo está grabando."),
        ]
    )
}
